### ISSUE TITLE
Make ReplacementData#getData() arrays take config data from YML file

### ISSUE THREAD

**Issue by phptek** [sunnysideup/silverstripe-upgrade_silverstripe#2]
Makes it easier to add new ones, rather than to hack around a class file.

**Comment by sunnysideup** [comment]
@phptek Hi Russell - I did not get any further information from you ...

**Comment by phptek** [comment]
@sunnysideup Wow, this was a long time ago. Sorry, I have no idea for now. I'll close until such time as I need to re-open :-)
